sudo: required

language: ruby

services:
  - docker

script:
  - ./build_version.sh $PHP_VERSION
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -v

env:
  - PHP_VERSION=7.1.2
  - PHP_VERSION=7.1.3
  - PHP_VERSION=7.1.6
  - PHP_VERSION=7.1.10
  - PHP_VERSION=7.1.11
  - PHP_VERSION=7.0.16
  - PHP_VERSION=7.0.17
  - PHP_VERSION=7.0.20
  - PHP_VERSION=7.0.24
  - PHP_VERSION=7.0.25
  - PHP_VERSION=5.6.30
  - PHP_VERSION=5.6.31
  - PHP_VERSION=5.6.32
  - PHP_VERSION=5.5.38

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: ./push_version.sh ${PHP_VERSION}
  on:
    branch: master
