sudo: required

language: ruby

services:
  - docker

script:
  - ./build_version.sh $PHP_VERSION
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -i
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -v

env:
  - PHP_VERSION=7.2.29 PHP_VERSION_ALIAS=7.2
  - PHP_VERSION=7.2.28
  - PHP_VERSION=7.2.27
  - PHP_VERSION=7.2.23
  - PHP_VERSION=7.2.22
  - PHP_VERSION=7.2.21
  - PHP_VERSION=7.2.20
  - PHP_VERSION=7.2.19
  - PHP_VERSION=7.2.18
  - PHP_VERSION=7.2.17
  - PHP_VERSION=7.2.16
  - PHP_VERSION=7.2.15
  - PHP_VERSION=7.2.14
  - PHP_VERSION=7.2.13
  - PHP_VERSION=7.2.12
  - PHP_VERSION=7.2.11
  - PHP_VERSION=7.2.10
  - PHP_VERSION=7.2.9
  - PHP_VERSION=7.2.8
  - PHP_VERSION=7.2.7
  - PHP_VERSION=7.2.6
  - PHP_VERSION=7.2.5
  - PHP_VERSION=7.2.4
  - PHP_VERSION=7.2.3
  - PHP_VERSION=7.2.2
  - PHP_VERSION=7.2.1
  - PHP_VERSION=7.2.0

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: ./push_version.sh ${PHP_VERSION} ${PHP_VERSION_ALIAS}
  on:
    branch: release/7.2
