sudo: required

language: ruby

services:
  - docker

script:
  - ./build_version.sh $PHP_VERSION
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -i
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -v

env:
  - PHP_VERSION=7.1.26 PHP_VERSION_ALIAS=7.1
  - PHP_VERSION=7.1.25
  - PHP_VERSION=7.1.24
  - PHP_VERSION=7.1.23
  - PHP_VERSION=7.1.22
  - PHP_VERSION=7.1.21
  - PHP_VERSION=7.1.20
  - PHP_VERSION=7.1.19
  - PHP_VERSION=7.1.18
  - PHP_VERSION=7.1.17
  - PHP_VERSION=7.1.16
  - PHP_VERSION=7.1.15
  - PHP_VERSION=7.1.14
  - PHP_VERSION=7.1.13
  - PHP_VERSION=7.1.12
  - PHP_VERSION=7.1.11
  - PHP_VERSION=7.1.10
  - PHP_VERSION=7.1.6
  - PHP_VERSION=7.1.3
  - PHP_VERSION=7.1.2

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: ./push_version.sh ${PHP_VERSION} ${PHP_VERSION_ALIAS}
  on:
    branch: release/7.1
