sudo: required

language: ruby

services:
  - docker

script:
  - ./build_version.sh $PHP_VERSION
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -i
  - docker run --rm -it exozet/php-fpm:${PHP_VERSION} php -v

env:
  - PHP_VERSION=7.0.32 PHP_VERSION_ALIAS=7.0
  - PHP_VERSION=7.0.31
  - PHP_VERSION=7.0.30
  - PHP_VERSION=7.0.29
  - PHP_VERSION=7.0.28
  - PHP_VERSION=7.0.27
  - PHP_VERSION=7.0.26
  - PHP_VERSION=7.0.26
  - PHP_VERSION=7.0.25
  - PHP_VERSION=7.0.24
  - PHP_VERSION=7.0.23
  - PHP_VERSION=7.0.22
  - PHP_VERSION=7.0.20
  - PHP_VERSION=7.0.17
  - PHP_VERSION=7.0.16

before_deploy:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"

deploy:
  provider: script
  script: ./push_version.sh ${PHP_VERSION} ${PHP_VERSION_ALIAS}
  on:
    branch: master
